import { formatCompactDate } from "@meshrix/ui-console/console-format-utils";
import { useServerConsoleShellContext } from "@meshrix/ui-console/server-console-shell-context";
import {
  maintenanceAgentRiskLabel,
  maintenanceAgentStatusLabel,
  maintenanceAgentStatusTone,
} from "./console-status-utils";

export function useMaintenanceAgentViewConsole() : any {
  const {
    addMaintenanceAgentSchedule,
    approveMaintenanceAgentRun,
    autoApproveRiskOptionBarOptions,
    isBusy,
    canAdminMaintenanceAgent,
    canApproveMaintenanceAgent,
    canRunMaintenanceAgent,
    cancelMaintenanceAgentRun,
    displayedMaintenanceAgentRuns,
    enabledBooleanOptionBarOptions,
    latestMaintenanceAgentRun,
    maintenanceAgentConfig,
    maintenanceAgentResultJson,
    maintenanceAgentRunbook,
    maintenanceAgentRunbookOptionBarOptions,
    maintenanceAgentRunbooks,
    maintenanceAgentSummary,
    nextMaintenanceAgentRunAt,
    pendingMaintenanceApprovalCount,
    plannerModeOptionBarOptions,
    removeMaintenanceAgentSchedule,
    runMaintenanceAgentGatewayReview,
    runMaintenanceAgentRunbook,
    saveMaintenanceAgentConfig,
    selectedMaintenanceAgentRun,
  } = useServerConsoleShellContext();

  return {
    addMaintenanceAgentSchedule,
    approveMaintenanceAgentRun,
    autoApproveRiskOptionBarOptions,
    isBusy,
    canAdminMaintenanceAgent,
    canApproveMaintenanceAgent,
    canRunMaintenanceAgent,
    cancelMaintenanceAgentRun,
    displayedMaintenanceAgentRuns,
    enabledBooleanOptionBarOptions,
    formatCompactDate,
    latestMaintenanceAgentRun,
    maintenanceAgentConfig,
    maintenanceAgentResultJson,
    maintenanceAgentRiskLabel,
    maintenanceAgentRunbook,
    maintenanceAgentRunbookOptionBarOptions,
    maintenanceAgentRunbooks,
    maintenanceAgentStatusLabel,
    maintenanceAgentStatusTone,
    maintenanceAgentSummary,
    nextMaintenanceAgentRunAt,
    pendingMaintenanceApprovalCount,
    plannerModeOptionBarOptions,
    removeMaintenanceAgentSchedule,
    runMaintenanceAgentGatewayReview,
    runMaintenanceAgentRunbook,
    saveMaintenanceAgentConfig,
    selectedMaintenanceAgentRun,
  };
}
