/**
 * CAPABILITIES GENERATED — DO NOT EDIT MANUALLY.
 *
 * Generated from: packages/contracts/src/operations/operation-registry.ts
 * Generator: tools/generators/generate-operation-artifacts.ts
 * Hash: sha256:74ee255852cd9366
 * Generated at: 2026-06-30T09:41:12.260Z
 *
 * To modify capabilities: edit source operation definitions or Operation Permission catalog mappings, then run the generator.
 */
export const GENERATED_CAPABILITIES_HASH = "sha256:74ee255852cd9366";

export const KERNEL_API_OPERATION_IDS = Object.freeze([
  "cap:api:readiness.baseline.status",
  "cap:api:authorization.subject.resolve",
  "cap:api:authorization.policy.evaluate",
  "cap:api:authorization.governance.summary",
  "cap:api:authorization.organization_governance.get",
  "cap:api:authorization.organization_governance.import",
  "cap:api:authorization.organization_governance.preview",
  "cap:api:authorization.organization_governance.publish",
  "cap:api:tag_management.tags.list",
  "cap:api:tag_management.tags.get",
  "cap:api:tag_management.tags.upsert",
  "cap:api:tag_management.tags.archive",
  "cap:api:tag_management.tags.restore",
  "cap:api:tag_management.projections.list",
  "cap:api:tag_management.projections.rebuild",
  "cap:api:tag_management.audit.list",
  "cap:api:authorization.roles.list",
  "cap:api:authorization.roles.upsert",
  "cap:api:authorization.departments.list",
  "cap:api:authorization.departments.upsert",
  "cap:api:authorization.teams.list",
  "cap:api:authorization.teams.upsert",
  "cap:api:authorization.users.policies.list",
  "cap:api:authorization.users.policy.upsert",
  "cap:api:authorization.agent_groups.list",
  "cap:api:authorization.agent_groups.upsert",
  "cap:api:authorization.agents.bindings.list",
  "cap:api:authorization.agents.binding.upsert",
  "cap:api:authorization.approvals.list",
  "cap:api:authorization.approvals.upsert",
  "cap:api:authorization.approvals.revoke",
  "cap:api:authorization.receipts.list",
  "cap:api:authorization.loan_records.list",
  "cap:api:authorization.denied_requests.list",
  "cap:api:workspace.info",
  "cap:api:workspace.file.upload",
  "cap:api:workspace.file.list",
  "cap:api:workspace.file.download",
  "cap:api:workspace.file.read",
  "cap:api:workspace.file.write",
  "cap:api:workspace.file.patch",
  "cap:api:workspace.contribution.submit",
  "cap:api:workspace.contribution.list",
  "cap:api:workspace.contribution.leaderboard",
  "cap:api:workspace.contribution.stats",
  "cap:api:workspace.contribution.report",
  "cap:api:workspace.contribution.assets.list",
  "cap:api:workspace.contribution.permission.request",
  "cap:api:workspace.contribution.permission.grant",
  "cap:api:workspace.contribution.scan",
  "cap:api:workspace.contribution.review",
  "cap:api:workspace.contribution.preview",
  "cap:api:workspace.contribution.publish",
  "cap:api:workspace.contribution.adopt",
  "cap:api:workspace.contribution.reject",
  "cap:api:workspace.contribution.request_changes",
  "cap:api:workspace.contribution.revoke",
  "cap:api:workspace.proposal.create",
  "cap:api:workspace.proposal.apply",
  "cap:api:workspace.asset.policy.set",
  "cap:api:workspace.asset.permission.check",
  "cap:api:workspace.asset.target.connect",
  "cap:api:workspace.asset.list",
  "cap:api:workspace.asset.read",
  "cap:api:workspace.asset.submit",
  "cap:api:workspace.asset.mutate",
  "cap:api:workspace.asset.sync.plan",
  "cap:api:workspace.asset.sync.apply",
  "cap:api:workspace.asset.import",
  "cap:api:workspace.asset.export",
  "cap:api:workspace.asset.review.comment",
  "cap:api:workspace.asset.review.requestChanges",
  "cap:api:workspace.asset.review.approve",
  "cap:api:workspace.asset.checkpoint",
  "cap:api:workspace.asset.lineage",
  "cap:api:workspace.asset.receipt.get",
  "cap:api:workspace.asset.backfill",
  "cap:api:workspace.audit.query",
  "cap:api:workspace.operation.history",
  "cap:api:workspace.checkpoint.tree.list",
  "cap:api:workspace.checkpoint.node.get",
  "cap:api:workspace.checkpoint.diff",
  "cap:api:workspace.checkpoint.restore.preview",
  "cap:api:workspace.checkpoint.restore",
  "cap:api:workspace.checkpoint.scope.query",
  "cap:api:workspace.operation.revert.scope",
  "cap:api:workspace.operation.revert.apply",
  "cap:api:external_services.publications.list",
  "cap:api:external_services.publications.get",
  "cap:api:external_services.create",
  "cap:api:external_services.replace",
  "cap:api:external_services.disable",
  "cap:api:external_services.remove",
  "cap:api:external_services.republish",
  "cap:api:external_services.list",
  "cap:api:external_services.get",
  "cap:api:external_services.health",
  "cap:api:gateway.policy.preview",
  "cap:api:gateway.forward",
  "cap:api:gateway.payload.transit",
  "cap:api:gateway.artifacts.get",
  "cap:api:gateway.audit",
  "cap:api:gateway.metrics",
  "cap:api:security_alerts.list",
  "cap:api:security_alerts.ack",
  "cap:api:security_alerts.export",
  "cap:api:security_alerts.prune",
  "cap:api:system.health",
  "cap:api:system.bootstrap",
  "cap:api:system.interfaces",
  "cap:api:appearance_presets.list",
  "cap:api:appearance_presets.import",
  "cap:api:production.health",
  "cap:api:architecture.live_map",
  "cap:api:sample_capability_pack.list",
  "cap:api:sample_capability_pack.get",
  "cap:api:sample_capability_pack.materialize",
  "cap:api:executive_report.list",
  "cap:api:executive_report.preview",
  "cap:api:executive_report.generate",
  "cap:api:operation_semantics.static_families.list",
  "cap:api:operation_semantics.static_families.get",
  "cap:api:workspace_governance.describe",
  "cap:api:workspace_governance.policy.set",
  "cap:api:workspace_governance.evaluate",
  "cap:api:workspace_governance.share_grant",
  "cap:api:events.subscribe",
  "cap:api:agent_sync.config.get",
  "cap:api:agent_sync.config.set",
  "cap:api:agent_sync.publish",
  "cap:api:agent_sync.subscribe",
  "cap:api:system.console_state",
  "cap:api:auth.session",
  "cap:api:auth.login",
  "cap:api:auth.logout",
  "cap:api:auth.users",
  "cap:api:auth.users.create",
  "cap:api:auth.users.update",
  "cap:api:auth.roles.get",
  "cap:api:auth.oidc.get",
  "cap:api:auth.oidc.set",
  "cap:api:auth.audit",
  "cap:api:auth.audit.export",
  "cap:api:auth.audit.retention.get",
  "cap:api:auth.audit.retention.set",
  "cap:api:auth.audit.prune",
  "cap:api:observability.trace.get",
  "cap:api:auth.sessions",
  "cap:api:auth.sessions.rotate",
  "cap:api:auth.sessions.revoke",
  "cap:api:process_identity.bootstrap_claim",
  "cap:api:process_identity.package.rotate",
  "cap:api:process_identity.package.revoke",
  "cap:api:discovery.check_in",
  "cap:api:discovery.clients",
  "cap:api:discovery.clients.alignment_command",
  "cap:api:discovery.get_config",
  "cap:api:discovery.set_config",
  "cap:api:runtime.info",
  "cap:api:runtime.assembly.build",
  "cap:api:runtime.gateway_channels",
  "cap:api:runtime.gateway_channels.select",
  "cap:api:runtime.path_browse",
  "cap:api:runtime.mounts",
  "cap:api:runtime.set_mounts",
  "cap:api:runtime.reload_mounts",
  "cap:api:settings.get",
  "cap:api:settings.set",
  "cap:api:strategy.describe",
  "cap:api:strategy.workflow_policy.evaluate",
  "cap:api:strategy.agent_policy.evaluate",
  "cap:api:strategy.route_policy.evaluate",
  "cap:api:strategy.queue_policy.evaluate",
  "cap:api:strategy.tool_policy.preview",
  "cap:api:operation_permission.api_keys.issuer_scopes",
  "cap:api:operation_permission.api_keys.list",
  "cap:api:operation_permission.api_keys.create",
  "cap:api:operation_permission.api_keys.rotate",
  "cap:api:operation_permission.api_keys.revoke",
  "cap:api:operation_permission.catalog",
  "cap:api:operation_permission.catalog_item",
  "cap:api:operation_permission.toolsets",
  "cap:api:operation_permission.toolsets_resolve",
  "cap:api:operation_permission.profiles",
  "cap:api:operation_permission.policy_evaluate",
  "cap:api:operation_permission.policy_preview",
  "cap:api:operation_permission.execute",
  "cap:api:operation_permission.batch",
  "cap:api:operation_permission.dry_run",
  "cap:api:operation_permission.grants",
  "cap:api:operation_permission.create_grant",
  "cap:api:operation_permission.update_grant",
  "cap:api:operation_permission.rotate_grant",
  "cap:api:operation_permission.revoke_grant",
  "cap:api:operation_permission.audit",
  "cap:api:operation_permission.audit_item",
  "cap:api:operation_permission.metrics_summary",
  "cap:api:operation_permission.metrics_export",
  "cap:api:operation_permission.metrics_health",
  "cap:api:operation_permission.metrics_prometheus",
  "cap:api:operation_permission.metrics_storage",
  "cap:api:operation_permission.metrics_prune",
  "cap:api:operation_permission.events",
  "cap:api:operation_permission.pending_operations.list",
  "cap:api:operation_permission.pending_operations.resolve",
  "cap:api:storage.summary",
  "cap:api:storage.doctor",
  "cap:api:storage.reconcile",
  "cap:api:storage.backups.list",
  "cap:api:storage.backups.create",
  "cap:api:storage.backups.retention",
  "cap:api:storage.backups.restore_preview",
  "cap:api:storage.backups.restore",
  "cap:api:system.background_processes",
  "cap:api:system.checkpoint_trees.list",
  "cap:api:system.checkpoint_trees.get",
  "cap:api:system.monitor_alerts.get",
  "cap:api:system.monitor_alerts.set",
  "cap:api:system.monitor_alerts.ack",
  "cap:api:system.background_supervisor.recover",
  "cap:api:agent_workspaces.create",
  "cap:api:agent_workspaces.list",
  "cap:api:agent_workspaces.get",
  "cap:api:agent_workspaces.delete",
  "cap:api:agent_workspaces.folder.create",
  "cap:api:agent_sessions.list",
  "cap:api:agent_sessions.get",
  "cap:api:agent_sessions.context.get",
  "cap:api:agent_sessions.events.append",
  "cap:api:agent_sessions.fork",
  "cap:api:agent_sessions.compare",
  "cap:api:agent_sessions.merge_proposal",
  "cap:api:agent_sessions.archive",
  "cap:api:agent_workspaces.submissions.resolve",
  "cap:api:agent_workspaces.issues.resolve",
  "cap:api:agent_workspaces.locks.list",
  "cap:api:agent_workspaces.locks.write",
  "cap:api:agent_workspaces.files.list",
  "cap:api:agent_workspaces.file.upload",
  "cap:api:agent_workspaces.file.stat",
  "cap:api:agent_workspaces.file.download",
  "cap:api:agent_workspaces.file.write",
  "cap:api:agent_workspaces.file.delete",
  "cap:api:agent_workspaces.file.move",
  "cap:api:agent_workspaces.context.get",
  "cap:api:agent_workspaces.context_bundle.export",
  "cap:api:agent_workspaces.context_bundle.restore",
  "cap:api:agent_workspaces.chain.get",
  "cap:api:agent_workspaces.parent.set",
  "cap:api:agent_workspaces.profile.hotswap",
  "cap:api:agent_workspaces.sources.set",
  "cap:api:agent_workspaces.share",
  "cap:api:agent_workspaces.unshare",
  "cap:api:context.profiles.get",
  "cap:api:context.profiles.set",
  "cap:api:context.preview",
  "cap:api:context.compaction.preview",
  "cap:api:context.compaction.run",
  "cap:api:context.compaction.records",
  "cap:api:context.session_memory.get",
  "cap:api:context.session_memory.clear",
  "cap:api:context.build_records",
  "cap:api:context.evaluation.runs.create",
  "cap:api:uploads.create_session",
  "cap:api:uploads.get_session",
  "cap:api:uploads.upload_chunk",
  "cap:api:jobs.create",
  "cap:api:jobs.upload_workspace_materialize",
  "cap:api:jobs.upload_workspace_materialization_cancel",
  "cap:api:jobs.list",
  "cap:api:jobs.failed_review",
  "cap:api:jobs.work_queue.inspect",
  "cap:api:jobs.work_queue.pause",
  "cap:api:jobs.work_queue.resume",
  "cap:api:jobs.work_queue.drain",
  "cap:api:jobs.work_queue.recover_failed",
  "cap:api:jobs.work_queue.rebuild",
  "cap:api:jobs.get",
  "cap:api:jobs.reparse",
  "cap:api:jobs.cancel",
  "cap:api:jobs.delete",
  "cap:api:jobs.result",
  "cap:api:jobs.normalized_documents",
  "cap:api:jobs.normalized_document.get",
  "cap:api:raw_objects.get",
  "cap:api:mcp.request"
].map(id => id.replace("cap:api:", "")));

export const KERNEL_TOOL_IDS = Object.freeze([
  "cap:tool:meshrix.readiness.baseline.status:execute",
  "cap:tool:meshrix.authorization.subject.resolve:execute",
  "cap:tool:meshrix.authorization.policy.evaluate:execute",
  "cap:tool:meshrix.authorization.governance.summary:execute",
  "cap:tool:meshrix.authorization.organizationGovernance.get:execute",
  "cap:tool:meshrix.authorization.organizationGovernance.import:execute",
  "cap:tool:meshrix.authorization.organizationGovernance.preview:execute",
  "cap:tool:meshrix.authorization.organizationGovernance.publish:execute",
  "cap:tool:meshrix.tagManagement.tags.list:execute",
  "cap:tool:meshrix.tagManagement.tags.get:execute",
  "cap:tool:meshrix.tagManagement.tags.upsert:execute",
  "cap:tool:meshrix.tagManagement.tags.archive:execute",
  "cap:tool:meshrix.tagManagement.tags.restore:execute",
  "cap:tool:meshrix.tagManagement.projections.list:execute",
  "cap:tool:meshrix.tagManagement.projections.rebuild:execute",
  "cap:tool:meshrix.tagManagement.audit.list:execute",
  "cap:tool:meshrix.authorization.roles.list:execute",
  "cap:tool:meshrix.authorization.roles.upsert:execute",
  "cap:tool:meshrix.authorization.departments.list:execute",
  "cap:tool:meshrix.authorization.departments.upsert:execute",
  "cap:tool:meshrix.authorization.teams.list:execute",
  "cap:tool:meshrix.authorization.teams.upsert:execute",
  "cap:tool:meshrix.authorization.users.policies.list:execute",
  "cap:tool:meshrix.authorization.users.policy.upsert:execute",
  "cap:tool:meshrix.authorization.agentGroups.list:execute",
  "cap:tool:meshrix.authorization.agentGroups.upsert:execute",
  "cap:tool:meshrix.authorization.agents.bindings.list:execute",
  "cap:tool:meshrix.authorization.agents.binding.upsert:execute",
  "cap:tool:meshrix.authorization.approvals.list:execute",
  "cap:tool:meshrix.authorization.approvals.upsert:execute",
  "cap:tool:meshrix.authorization.approvals.revoke:execute",
  "cap:tool:meshrix.authorization.receipts.list:execute",
  "cap:tool:meshrix.authorization.loanRecords.list:execute",
  "cap:tool:meshrix.authorization.deniedRequests.list:execute",
  "cap:tool:meshrix.workspace.info:execute",
  "cap:tool:meshrix.workspace.file.upload:execute",
  "cap:tool:meshrix.workspace.file.list:execute",
  "cap:tool:meshrix.workspace.file.download:execute",
  "cap:tool:meshrix.workspace.file.read:execute",
  "cap:tool:meshrix.workspace.file.write:execute",
  "cap:tool:meshrix.workspace.file.patch:execute",
  "cap:tool:meshrix.workspace.contribution.submit:execute",
  "cap:tool:meshrix.workspace.contribution.list:execute",
  "cap:tool:meshrix.workspace.contribution.leaderboard:execute",
  "cap:tool:meshrix.workspace.contribution.stats:execute",
  "cap:tool:meshrix.workspace.contribution.report:execute",
  "cap:tool:meshrix.workspace.contribution.assets.list:execute",
  "cap:tool:meshrix.workspace.contribution.permission.request:execute",
  "cap:tool:meshrix.workspace.contribution.permission.grant:execute",
  "cap:tool:meshrix.workspace.contribution.scan:execute",
  "cap:tool:meshrix.workspace.contribution.review:execute",
  "cap:tool:meshrix.workspace.contribution.preview:execute",
  "cap:tool:meshrix.workspace.contribution.publish:execute",
  "cap:tool:meshrix.workspace.contribution.adopt:execute",
  "cap:tool:meshrix.workspace.contribution.reject:execute",
  "cap:tool:meshrix.workspace.contribution.requestChanges:execute",
  "cap:tool:meshrix.workspace.contribution.revoke:execute",
  "cap:tool:meshrix.workspace.proposal.create:execute",
  "cap:tool:meshrix.workspace.proposal.apply:execute",
  "cap:tool:meshrix.workspace.asset.policy.set:execute",
  "cap:tool:meshrix.workspace.asset.permission.check:execute",
  "cap:tool:meshrix.workspace.asset.target.connect:execute",
  "cap:tool:meshrix.workspace.asset.list:execute",
  "cap:tool:meshrix.workspace.asset.read:execute",
  "cap:tool:meshrix.workspace.asset.submit:execute",
  "cap:tool:meshrix.workspace.asset.mutate:execute",
  "cap:tool:meshrix.workspace.asset.sync.plan:execute",
  "cap:tool:meshrix.workspace.asset.sync.apply:execute",
  "cap:tool:meshrix.workspace.asset.import:execute",
  "cap:tool:meshrix.workspace.asset.export:execute",
  "cap:tool:meshrix.workspace.asset.review.comment:execute",
  "cap:tool:meshrix.workspace.asset.review.requestChanges:execute",
  "cap:tool:meshrix.workspace.asset.review.approve:execute",
  "cap:tool:meshrix.workspace.asset.checkpoint:execute",
  "cap:tool:meshrix.workspace.asset.lineage:execute",
  "cap:tool:meshrix.workspace.asset.receipt.get:execute",
  "cap:tool:meshrix.workspace.asset.backfill:execute",
  "cap:tool:meshrix.workspace.audit.query:execute",
  "cap:tool:meshrix.workspace.operation.history:execute",
  "cap:tool:meshrix.workspace.checkpoint.tree.list:execute",
  "cap:tool:meshrix.workspace.checkpoint.node.get:execute",
  "cap:tool:meshrix.workspace.checkpoint.diff:execute",
  "cap:tool:meshrix.workspace.checkpoint.restore.preview:execute",
  "cap:tool:meshrix.workspace.checkpoint.restore:execute",
  "cap:tool:meshrix.workspace.checkpoint.scope.query:execute",
  "cap:tool:meshrix.workspace.operation.revert.scope:execute",
  "cap:tool:meshrix.workspace.operation.revert.apply:execute",
  "cap:tool:meshrix.gateway.externalServices.publications.list:execute",
  "cap:tool:meshrix.gateway.externalServices.publications.get:execute",
  "cap:tool:meshrix.gateway.externalServices.create:execute",
  "cap:tool:meshrix.gateway.externalServices.replace:execute",
  "cap:tool:meshrix.gateway.externalServices.disable:execute",
  "cap:tool:meshrix.gateway.externalServices.remove:execute",
  "cap:tool:meshrix.gateway.externalServices.republish:execute",
  "cap:tool:meshrix.gateway.externalServices.list:execute",
  "cap:tool:meshrix.gateway.externalServices.get:execute",
  "cap:tool:meshrix.gateway.externalServices.health:execute",
  "cap:tool:meshrix.gateway.policyPreview:execute",
  "cap:tool:meshrix.gateway.forward:execute",
  "cap:tool:meshrix.gateway.payloadTransit:execute",
  "cap:tool:meshrix.gateway.artifacts.get:execute",
  "cap:tool:meshrix.gateway.audit:execute",
  "cap:tool:meshrix.gateway.metrics:execute",
  "cap:tool:meshrix.securityAlerts.list:execute",
  "cap:tool:meshrix.securityAlerts.ack:execute",
  "cap:tool:meshrix.securityAlerts.export:execute",
  "cap:tool:meshrix.securityAlerts.prune:execute",
  "cap:tool:system.health:execute",
  "cap:tool:meshrix.architecture.liveMap:execute",
  "cap:tool:meshrix.sampleCapabilityPack.list:execute",
  "cap:tool:meshrix.sampleCapabilityPack.get:execute",
  "cap:tool:meshrix.sampleCapabilityPack.materialize:execute",
  "cap:tool:meshrix.executiveReport.list:execute",
  "cap:tool:meshrix.executiveReport.preview:execute",
  "cap:tool:meshrix.executiveReport.generate:execute",
  "cap:tool:meshrix.workspaceGovernance.describe:execute",
  "cap:tool:meshrix.workspaceGovernance.policy.set:execute",
  "cap:tool:meshrix.workspaceGovernance.evaluate:execute",
  "cap:tool:meshrix.workspaceGovernance.shareGrant:execute",
  "cap:tool:meshrix.agentSync.config.get:execute",
  "cap:tool:meshrix.agentSync.config.set:execute",
  "cap:tool:meshrix.agentSync.publish:execute",
  "cap:tool:meshrix.agentSync.subscribe:execute",
  "cap:tool:meshrix.runtime.info:execute",
  "cap:tool:meshrix.runtime.mounts:execute",
  "cap:tool:meshrix.runtime.mounts.set:execute",
  "cap:tool:meshrix.runtime.mounts.reload:execute",
  "cap:tool:meshrix.strategy.describe:execute",
  "cap:tool:meshrix.strategy.workflowPolicy.evaluate:execute",
  "cap:tool:meshrix.strategy.agentPolicy.evaluate:execute",
  "cap:tool:meshrix.strategy.routePolicy.evaluate:execute",
  "cap:tool:meshrix.strategy.queuePolicy.evaluate:execute",
  "cap:tool:meshrix.strategy.toolPolicy.preview:execute",
  "cap:tool:meshrix.operationPermission.apiKeys.issuerScopes:execute",
  "cap:tool:meshrix.operationPermission.apiKeys.list:execute",
  "cap:tool:meshrix.operationPermission.apiKeys.create:execute",
  "cap:tool:meshrix.operationPermission.apiKeys.rotate:execute",
  "cap:tool:meshrix.operationPermission.apiKeys.revoke:execute",
  "cap:tool:meshrix.operationPermission.catalog:execute",
  "cap:tool:meshrix.operationPermission.catalogItem:execute",
  "cap:tool:meshrix.operationPermission.toolsets:execute",
  "cap:tool:meshrix.operationPermission.toolsetsResolve:execute",
  "cap:tool:meshrix.operationPermission.profiles:execute",
  "cap:tool:meshrix.operationPermission.policyEvaluate:execute",
  "cap:tool:meshrix.operationPermission.policyPreview:execute",
  "cap:tool:meshrix.operationPermission.grants:execute",
  "cap:tool:meshrix.operationPermission.createGrant:execute",
  "cap:tool:meshrix.operationPermission.updateGrant:execute",
  "cap:tool:meshrix.operationPermission.rotateGrant:execute",
  "cap:tool:meshrix.operationPermission.revokeGrant:execute",
  "cap:tool:meshrix.operationPermission.audit:execute",
  "cap:tool:meshrix.operationPermission.auditItem:execute",
  "cap:tool:meshrix.operationPermission.metricsSummary:execute",
  "cap:tool:meshrix.operationPermission.metricsExport:execute",
  "cap:tool:meshrix.operationPermission.metricsHealth:execute",
  "cap:tool:meshrix.operationPermission.metricsPrometheus:execute",
  "cap:tool:meshrix.operationPermission.metricsStorage:execute",
  "cap:tool:meshrix.operationPermission.metricsPrune:execute",
  "cap:tool:meshrix.operationPermission.events:execute",
  "cap:tool:meshrix.operationPermission.pendingOperations.list:execute",
  "cap:tool:meshrix.operationPermission.pendingOperations.resolve:execute",
  "cap:tool:meshrix.storageSummary:execute",
  "cap:tool:meshrix.storageBackups.list:execute",
  "cap:tool:meshrix.storageBackups.create:execute",
  "cap:tool:meshrix.storageBackups.restorePreview:execute",
  "cap:tool:meshrix.storageBackups.restore:execute",
  "cap:tool:meshrix.agentWorkspace.create:execute",
  "cap:tool:meshrix.workspace.create:execute",
  "cap:tool:meshrix.agentWorkspace.list:execute",
  "cap:tool:meshrix.agentWorkspace.get:execute",
  "cap:tool:meshrix.agentWorkspace.delete:execute",
  "cap:tool:meshrix.agentWorkspace.folder.create:execute",
  "cap:tool:meshrix.workspace.folder.create:execute",
  "cap:tool:meshrix.agentSession.list:execute",
  "cap:tool:meshrix.agentSession.get:execute",
  "cap:tool:meshrix.agentSession.context:execute",
  "cap:tool:meshrix.agentSession.events.append:execute",
  "cap:tool:meshrix.agentSession.fork:execute",
  "cap:tool:meshrix.agentSession.compare:execute",
  "cap:tool:meshrix.agentSession.mergeProposal:execute",
  "cap:tool:meshrix.agentSession.archive:execute",
  "cap:tool:meshrix.agentWorkspace.submissionResolve:execute",
  "cap:tool:meshrix.agentWorkspace.issueResolve:execute",
  "cap:tool:meshrix.agentWorkspace.locks:execute",
  "cap:tool:meshrix.agentWorkspace.lock:execute",
  "cap:tool:meshrix.agentWorkspace.files.list:execute",
  "cap:tool:meshrix.workspace.files.list:execute",
  "cap:tool:meshrix.agentWorkspace.file.upload:execute",
  "cap:tool:meshrix.agentWorkspace.file.stat:execute",
  "cap:tool:meshrix.workspace.file.stat:execute",
  "cap:tool:meshrix.agentWorkspace.file.download:execute",
  "cap:tool:meshrix.agentWorkspace.file.write:execute",
  "cap:tool:meshrix.agentWorkspace.file.delete:execute",
  "cap:tool:meshrix.workspace.file.delete:execute",
  "cap:tool:meshrix.agentWorkspace.file.move:execute",
  "cap:tool:meshrix.workspace.file.move:execute",
  "cap:tool:meshrix.agentWorkspace.context:execute",
  "cap:tool:meshrix.agentWorkspace.contextBundle.export:execute",
  "cap:tool:meshrix.agentWorkspace.contextBundle.restore:execute",
  "cap:tool:meshrix.agentWorkspace.chain:execute",
  "cap:tool:meshrix.agentWorkspace.parent.set:execute",
  "cap:tool:meshrix.agentWorkspace.profile.hotswap:execute",
  "cap:tool:meshrix.agentWorkspace.sources.set:execute",
  "cap:tool:meshrix.agentWorkspace.share:execute",
  "cap:tool:meshrix.agentWorkspace.unshare:execute",
  "cap:tool:meshrix.context.profiles:execute",
  "cap:tool:meshrix.context.profiles.set:execute",
  "cap:tool:meshrix.agentMemory.sessionMemory.get:execute",
  "cap:tool:meshrix.agentMemory.sessionMemory.clear:execute",
  "cap:tool:uploads.create_session:execute",
  "cap:tool:uploads.get_session:execute",
  "cap:tool:uploads.upload_chunk:execute",
  "cap:tool:meshrix.jobs.uploadWorkspaceMaterialize:execute",
  "cap:tool:meshrix.jobs.list:execute",
  "cap:tool:meshrix.jobs.workQueue.inspect:execute",
  "cap:tool:meshrix.jobs.workQueue.pause:execute",
  "cap:tool:meshrix.jobs.workQueue.resume:execute",
  "cap:tool:meshrix.jobs.workQueue.drain:execute",
  "cap:tool:meshrix.jobs.workQueue.recoverFailed:execute",
  "cap:tool:meshrix.jobs.workQueue.rebuild:execute",
  "cap:tool:meshrix.jobs.get:execute"
].map(id => id.replace("cap:tool:", "").replace(":execute", "")));

export const KERNEL_CAPABILITY_WILDCARDS = Object.freeze([
  "cap:*",
  "cap:api:*",
  "cap:tool:*"
]);

export const KERNEL_API_CAPABILITY_PERMISSIONS = Object.freeze(
  KERNEL_API_OPERATION_IDS.map(id => `cap:api:${id}`)
);

export const KERNEL_TOOL_CAPABILITY_PERMISSIONS = Object.freeze(
  KERNEL_TOOL_IDS.map(id => `cap:tool:${id}:execute`)
);

export const KERNEL_CAPABILITY_PERMISSIONS = Object.freeze([
  ...KERNEL_API_CAPABILITY_PERMISSIONS,
  ...KERNEL_TOOL_CAPABILITY_PERMISSIONS
]);

export function apiCapabilityId(operationId: string) {
  return `cap:api:${String(operationId || "").trim()}`;
}

export function toolExecuteCapabilityId(toolId: string) {
  return `cap:tool:${String(toolId || "").trim()}:execute`;
}

export const CAPABILITY_RISK_MAP = Object.freeze({
  "cap:api:readiness.baseline.status": "read_only",
  "cap:api:authorization.subject.resolve": "read_only",
  "cap:api:authorization.policy.evaluate": "read_only",
  "cap:api:authorization.governance.summary": "read_only",
  "cap:api:authorization.organization_governance.get": "read_only",
  "cap:api:authorization.organization_governance.import": "read_only",
  "cap:api:authorization.organization_governance.preview": "read_only",
  "cap:api:authorization.organization_governance.publish": "repair_write",
  "cap:api:tag_management.tags.list": "read_only",
  "cap:api:tag_management.tags.get": "read_only",
  "cap:api:tag_management.tags.upsert": "repair_write",
  "cap:api:tag_management.tags.archive": "repair_write",
  "cap:api:tag_management.tags.restore": "repair_write",
  "cap:api:tag_management.projections.list": "read_only",
  "cap:api:tag_management.projections.rebuild": "repair_write",
  "cap:api:tag_management.audit.list": "read_only",
  "cap:api:authorization.roles.list": "read_only",
  "cap:api:authorization.roles.upsert": "repair_write",
  "cap:api:authorization.departments.list": "read_only",
  "cap:api:authorization.departments.upsert": "repair_write",
  "cap:api:authorization.teams.list": "read_only",
  "cap:api:authorization.teams.upsert": "repair_write",
  "cap:api:authorization.users.policies.list": "read_only",
  "cap:api:authorization.users.policy.upsert": "repair_write",
  "cap:api:authorization.agent_groups.list": "read_only",
  "cap:api:authorization.agent_groups.upsert": "repair_write",
  "cap:api:authorization.agents.bindings.list": "read_only",
  "cap:api:authorization.agents.binding.upsert": "repair_write",
  "cap:api:authorization.approvals.list": "read_only",
  "cap:api:authorization.approvals.upsert": "repair_write",
  "cap:api:authorization.approvals.revoke": "repair_write",
  "cap:api:authorization.receipts.list": "read_only",
  "cap:api:authorization.loan_records.list": "read_only",
  "cap:api:authorization.denied_requests.list": "read_only",
  "cap:api:workspace.info": "read_only",
  "cap:api:workspace.file.upload": "safe_write",
  "cap:api:workspace.file.list": "read_only",
  "cap:api:workspace.file.download": "read_only",
  "cap:api:workspace.file.read": "read_only",
  "cap:api:workspace.file.write": "safe_write",
  "cap:api:workspace.file.patch": "safe_write",
  "cap:api:workspace.contribution.submit": "safe_write",
  "cap:api:workspace.contribution.list": "read_only",
  "cap:api:workspace.contribution.leaderboard": "read_only",
  "cap:api:workspace.contribution.stats": "read_only",
  "cap:api:workspace.contribution.report": "read_only",
  "cap:api:workspace.contribution.assets.list": "read_only",
  "cap:api:workspace.contribution.permission.request": "safe_write",
  "cap:api:workspace.contribution.permission.grant": "repair_write",
  "cap:api:workspace.contribution.scan": "safe_write",
  "cap:api:workspace.contribution.review": "safe_write",
  "cap:api:workspace.contribution.preview": "safe_write",
  "cap:api:workspace.contribution.publish": "repair_write",
  "cap:api:workspace.contribution.adopt": "safe_write",
  "cap:api:workspace.contribution.reject": "repair_write",
  "cap:api:workspace.contribution.request_changes": "safe_write",
  "cap:api:workspace.contribution.revoke": "repair_write",
  "cap:api:workspace.proposal.create": "safe_write",
  "cap:api:workspace.proposal.apply": "repair_write",
  "cap:api:workspace.asset.policy.set": "repair_write",
  "cap:api:workspace.asset.permission.check": "read_only",
  "cap:api:workspace.asset.target.connect": "safe_write",
  "cap:api:workspace.asset.list": "read_only",
  "cap:api:workspace.asset.read": "read_only",
  "cap:api:workspace.asset.submit": "safe_write",
  "cap:api:workspace.asset.mutate": "safe_write",
  "cap:api:workspace.asset.sync.plan": "read_only",
  "cap:api:workspace.asset.sync.apply": "safe_write",
  "cap:api:workspace.asset.import": "safe_write",
  "cap:api:workspace.asset.export": "repair_write",
  "cap:api:workspace.asset.review.comment": "safe_write",
  "cap:api:workspace.asset.review.requestChanges": "safe_write",
  "cap:api:workspace.asset.review.approve": "safe_write",
  "cap:api:workspace.asset.checkpoint": "safe_write",
  "cap:api:workspace.asset.lineage": "read_only",
  "cap:api:workspace.asset.receipt.get": "read_only",
  "cap:api:workspace.asset.backfill": "repair_write",
  "cap:api:workspace.audit.query": "read_only",
  "cap:api:workspace.operation.history": "read_only",
  "cap:api:workspace.checkpoint.tree.list": "read_only",
  "cap:api:workspace.checkpoint.node.get": "read_only",
  "cap:api:workspace.checkpoint.diff": "read_only",
  "cap:api:workspace.checkpoint.restore.preview": "repair_write",
  "cap:api:workspace.checkpoint.restore": "repair_write",
  "cap:api:workspace.checkpoint.scope.query": "read_only",
  "cap:api:workspace.operation.revert.scope": "repair_write",
  "cap:api:workspace.operation.revert.apply": "repair_write",
  "cap:api:external_services.publications.list": "read_only",
  "cap:api:external_services.publications.get": "read_only",
  "cap:api:external_services.create": "safe_write",
  "cap:api:external_services.replace": "safe_write",
  "cap:api:external_services.disable": "safe_write",
  "cap:api:external_services.remove": "repair_write",
  "cap:api:external_services.republish": "safe_write",
  "cap:api:external_services.list": "read_only",
  "cap:api:external_services.get": "read_only",
  "cap:api:external_services.health": "read_only",
  "cap:api:gateway.policy.preview": "read_only",
  "cap:api:gateway.forward": "safe_write",
  "cap:api:gateway.payload.transit": "safe_write",
  "cap:api:gateway.artifacts.get": "read_only",
  "cap:api:gateway.audit": "read_only",
  "cap:api:gateway.metrics": "read_only",
  "cap:api:security_alerts.list": "read_only",
  "cap:api:security_alerts.ack": "safe_write",
  "cap:api:security_alerts.export": "read_only",
  "cap:api:security_alerts.prune": "repair_write",
  "cap:api:system.health": "read_only",
  "cap:api:system.bootstrap": "read_only",
  "cap:api:system.interfaces": "read_only",
  "cap:api:appearance_presets.list": "read_only",
  "cap:api:appearance_presets.import": "safe_write",
  "cap:api:production.health": "read_only",
  "cap:api:architecture.live_map": "read_only",
  "cap:api:sample_capability_pack.list": "read_only",
  "cap:api:sample_capability_pack.get": "read_only",
  "cap:api:sample_capability_pack.materialize": "safe_write",
  "cap:api:executive_report.list": "read_only",
  "cap:api:executive_report.preview": "read_only",
  "cap:api:executive_report.generate": "safe_write",
  "cap:api:operation_semantics.static_families.list": "read_only",
  "cap:api:operation_semantics.static_families.get": "read_only",
  "cap:api:workspace_governance.describe": "read_only",
  "cap:api:workspace_governance.policy.set": "repair_write",
  "cap:api:workspace_governance.evaluate": "safe_write",
  "cap:api:workspace_governance.share_grant": "safe_write",
  "cap:api:events.subscribe": "read_only",
  "cap:api:agent_sync.config.get": "read_only",
  "cap:api:agent_sync.config.set": "repair_write",
  "cap:api:agent_sync.publish": "safe_write",
  "cap:api:agent_sync.subscribe": "read_only",
  "cap:api:system.console_state": "read_only",
  "cap:api:auth.session": "read_only",
  "cap:api:auth.login": "safe_write",
  "cap:api:auth.logout": "safe_write",
  "cap:api:auth.users": "read_only",
  "cap:api:auth.users.create": "safe_write",
  "cap:api:auth.users.update": "repair_write",
  "cap:api:auth.roles.get": "read_only",
  "cap:api:auth.oidc.get": "read_only",
  "cap:api:auth.oidc.set": "repair_write",
  "cap:api:auth.audit": "read_only",
  "cap:api:auth.audit.export": "read_only",
  "cap:api:auth.audit.retention.get": "read_only",
  "cap:api:auth.audit.retention.set": "repair_write",
  "cap:api:auth.audit.prune": "repair_write",
  "cap:api:observability.trace.get": "read_only",
  "cap:api:auth.sessions": "read_only",
  "cap:api:auth.sessions.rotate": "safe_write",
  "cap:api:auth.sessions.revoke": "safe_write",
  "cap:api:process_identity.bootstrap_claim": "safe_write",
  "cap:api:process_identity.package.rotate": "safe_write",
  "cap:api:process_identity.package.revoke": "safe_write",
  "cap:api:discovery.check_in": "safe_write",
  "cap:api:discovery.clients": "read_only",
  "cap:api:discovery.clients.alignment_command": "repair_write",
  "cap:api:discovery.get_config": "read_only",
  "cap:api:discovery.set_config": "repair_write",
  "cap:api:runtime.info": "read_only",
  "cap:api:runtime.assembly.build": "safe_write",
  "cap:api:runtime.gateway_channels": "read_only",
  "cap:api:runtime.gateway_channels.select": "safe_write",
  "cap:api:runtime.path_browse": "safe_write",
  "cap:api:runtime.mounts": "read_only",
  "cap:api:runtime.set_mounts": "repair_write",
  "cap:api:runtime.reload_mounts": "repair_write",
  "cap:api:settings.get": "read_only",
  "cap:api:settings.set": "repair_write",
  "cap:api:strategy.describe": "read_only",
  "cap:api:strategy.workflow_policy.evaluate": "read_only",
  "cap:api:strategy.agent_policy.evaluate": "read_only",
  "cap:api:strategy.route_policy.evaluate": "read_only",
  "cap:api:strategy.queue_policy.evaluate": "read_only",
  "cap:api:strategy.tool_policy.preview": "read_only",
  "cap:api:operation_permission.api_keys.issuer_scopes": "read_only",
  "cap:api:operation_permission.api_keys.list": "read_only",
  "cap:api:operation_permission.api_keys.create": "repair_write",
  "cap:api:operation_permission.api_keys.rotate": "repair_write",
  "cap:api:operation_permission.api_keys.revoke": "repair_write",
  "cap:api:operation_permission.catalog": "read_only",
  "cap:api:operation_permission.catalog_item": "read_only",
  "cap:api:operation_permission.toolsets": "read_only",
  "cap:api:operation_permission.toolsets_resolve": "read_only",
  "cap:api:operation_permission.profiles": "read_only",
  "cap:api:operation_permission.policy_evaluate": "read_only",
  "cap:api:operation_permission.policy_preview": "read_only",
  "cap:api:operation_permission.execute": "safe_write",
  "cap:api:operation_permission.batch": "safe_write",
  "cap:api:operation_permission.dry_run": "read_only",
  "cap:api:operation_permission.grants": "read_only",
  "cap:api:operation_permission.create_grant": "repair_write",
  "cap:api:operation_permission.update_grant": "repair_write",
  "cap:api:operation_permission.rotate_grant": "repair_write",
  "cap:api:operation_permission.revoke_grant": "repair_write",
  "cap:api:operation_permission.audit": "read_only",
  "cap:api:operation_permission.audit_item": "read_only",
  "cap:api:operation_permission.metrics_summary": "read_only",
  "cap:api:operation_permission.metrics_export": "read_only",
  "cap:api:operation_permission.metrics_health": "read_only",
  "cap:api:operation_permission.metrics_prometheus": "read_only",
  "cap:api:operation_permission.metrics_storage": "read_only",
  "cap:api:operation_permission.metrics_prune": "repair_write",
  "cap:api:operation_permission.events": "read_only",
  "cap:api:operation_permission.pending_operations.list": "read_only",
  "cap:api:operation_permission.pending_operations.resolve": "repair_write",
  "cap:api:storage.summary": "read_only",
  "cap:api:storage.doctor": "read_only",
  "cap:api:storage.reconcile": "repair_write",
  "cap:api:storage.backups.list": "read_only",
  "cap:api:storage.backups.create": "safe_write",
  "cap:api:storage.backups.retention": "repair_write",
  "cap:api:storage.backups.restore_preview": "read_only",
  "cap:api:storage.backups.restore": "repair_write",
  "cap:api:system.background_processes": "read_only",
  "cap:api:system.checkpoint_trees.list": "read_only",
  "cap:api:system.checkpoint_trees.get": "read_only",
  "cap:api:system.monitor_alerts.get": "read_only",
  "cap:api:system.monitor_alerts.set": "safe_write",
  "cap:api:system.monitor_alerts.ack": "safe_write",
  "cap:api:system.background_supervisor.recover": "repair_write",
  "cap:api:agent_workspaces.create": "safe_write",
  "cap:api:agent_workspaces.list": "read_only",
  "cap:api:agent_workspaces.get": "read_only",
  "cap:api:agent_workspaces.delete": "safe_write",
  "cap:api:agent_workspaces.folder.create": "safe_write",
  "cap:api:agent_sessions.list": "read_only",
  "cap:api:agent_sessions.get": "read_only",
  "cap:api:agent_sessions.context.get": "read_only",
  "cap:api:agent_sessions.events.append": "safe_write",
  "cap:api:agent_sessions.fork": "safe_write",
  "cap:api:agent_sessions.compare": "read_only",
  "cap:api:agent_sessions.merge_proposal": "safe_write",
  "cap:api:agent_sessions.archive": "safe_write",
  "cap:api:agent_workspaces.submissions.resolve": "safe_write",
  "cap:api:agent_workspaces.issues.resolve": "safe_write",
  "cap:api:agent_workspaces.locks.list": "read_only",
  "cap:api:agent_workspaces.locks.write": "safe_write",
  "cap:api:agent_workspaces.files.list": "read_only",
  "cap:api:agent_workspaces.file.upload": "safe_write",
  "cap:api:agent_workspaces.file.stat": "read_only",
  "cap:api:agent_workspaces.file.download": "read_only",
  "cap:api:agent_workspaces.file.write": "safe_write",
  "cap:api:agent_workspaces.file.delete": "safe_write",
  "cap:api:agent_workspaces.file.move": "safe_write",
  "cap:api:agent_workspaces.context.get": "read_only",
  "cap:api:agent_workspaces.context_bundle.export": "read_only",
  "cap:api:agent_workspaces.context_bundle.restore": "safe_write",
  "cap:api:agent_workspaces.chain.get": "read_only",
  "cap:api:agent_workspaces.parent.set": "safe_write",
  "cap:api:agent_workspaces.profile.hotswap": "safe_write",
  "cap:api:agent_workspaces.sources.set": "safe_write",
  "cap:api:agent_workspaces.share": "repair_write",
  "cap:api:agent_workspaces.unshare": "safe_write",
  "cap:api:context.profiles.get": "read_only",
  "cap:api:context.profiles.set": "safe_write",
  "cap:api:context.preview": "safe_write",
  "cap:api:context.compaction.preview": "read_only",
  "cap:api:context.compaction.run": "safe_write",
  "cap:api:context.compaction.records": "read_only",
  "cap:api:context.session_memory.get": "read_only",
  "cap:api:context.session_memory.clear": "repair_write",
  "cap:api:context.build_records": "read_only",
  "cap:api:context.evaluation.runs.create": "safe_write",
  "cap:api:uploads.create_session": "safe_write",
  "cap:api:uploads.get_session": "read_only",
  "cap:api:uploads.upload_chunk": "safe_write",
  "cap:api:jobs.create": "safe_write",
  "cap:api:jobs.upload_workspace_materialize": "repair_write",
  "cap:api:jobs.upload_workspace_materialization_cancel": "safe_write",
  "cap:api:jobs.list": "read_only",
  "cap:api:jobs.failed_review": "read_only",
  "cap:api:jobs.work_queue.inspect": "read_only",
  "cap:api:jobs.work_queue.pause": "safe_write",
  "cap:api:jobs.work_queue.resume": "safe_write",
  "cap:api:jobs.work_queue.drain": "safe_write",
  "cap:api:jobs.work_queue.recover_failed": "safe_write",
  "cap:api:jobs.work_queue.rebuild": "repair_write",
  "cap:api:jobs.get": "read_only",
  "cap:api:jobs.reparse": "safe_write",
  "cap:api:jobs.cancel": "safe_write",
  "cap:api:jobs.delete": "repair_write",
  "cap:api:jobs.result": "read_only",
  "cap:api:jobs.normalized_documents": "read_only",
  "cap:api:jobs.normalized_document.get": "read_only",
  "cap:api:raw_objects.get": "read_only",
  "cap:api:mcp.request": "read_only",
  "cap:tool:meshrix.readiness.baseline.status:execute": "read_only",
  "cap:tool:meshrix.authorization.subject.resolve:execute": "read_only",
  "cap:tool:meshrix.authorization.policy.evaluate:execute": "read_only",
  "cap:tool:meshrix.authorization.governance.summary:execute": "read_only",
  "cap:tool:meshrix.authorization.organizationGovernance.get:execute": "read_only",
  "cap:tool:meshrix.authorization.organizationGovernance.import:execute": "read_only",
  "cap:tool:meshrix.authorization.organizationGovernance.preview:execute": "read_only",
  "cap:tool:meshrix.authorization.organizationGovernance.publish:execute": "repair_write",
  "cap:tool:meshrix.tagManagement.tags.list:execute": "read_only",
  "cap:tool:meshrix.tagManagement.tags.get:execute": "read_only",
  "cap:tool:meshrix.tagManagement.tags.upsert:execute": "repair_write",
  "cap:tool:meshrix.tagManagement.tags.archive:execute": "repair_write",
  "cap:tool:meshrix.tagManagement.tags.restore:execute": "repair_write",
  "cap:tool:meshrix.tagManagement.projections.list:execute": "read_only",
  "cap:tool:meshrix.tagManagement.projections.rebuild:execute": "repair_write",
  "cap:tool:meshrix.tagManagement.audit.list:execute": "read_only",
  "cap:tool:meshrix.authorization.roles.list:execute": "read_only",
  "cap:tool:meshrix.authorization.roles.upsert:execute": "repair_write",
  "cap:tool:meshrix.authorization.departments.list:execute": "read_only",
  "cap:tool:meshrix.authorization.departments.upsert:execute": "repair_write",
  "cap:tool:meshrix.authorization.teams.list:execute": "read_only",
  "cap:tool:meshrix.authorization.teams.upsert:execute": "repair_write",
  "cap:tool:meshrix.authorization.users.policies.list:execute": "read_only",
  "cap:tool:meshrix.authorization.users.policy.upsert:execute": "repair_write",
  "cap:tool:meshrix.authorization.agentGroups.list:execute": "read_only",
  "cap:tool:meshrix.authorization.agentGroups.upsert:execute": "repair_write",
  "cap:tool:meshrix.authorization.agents.bindings.list:execute": "read_only",
  "cap:tool:meshrix.authorization.agents.binding.upsert:execute": "repair_write",
  "cap:tool:meshrix.authorization.approvals.list:execute": "read_only",
  "cap:tool:meshrix.authorization.approvals.upsert:execute": "repair_write",
  "cap:tool:meshrix.authorization.approvals.revoke:execute": "repair_write",
  "cap:tool:meshrix.authorization.receipts.list:execute": "read_only",
  "cap:tool:meshrix.authorization.loanRecords.list:execute": "read_only",
  "cap:tool:meshrix.authorization.deniedRequests.list:execute": "read_only",
  "cap:tool:meshrix.workspace.info:execute": "read_only",
  "cap:tool:meshrix.workspace.file.upload:execute": "safe_write",
  "cap:tool:meshrix.workspace.file.list:execute": "read_only",
  "cap:tool:meshrix.workspace.file.download:execute": "read_only",
  "cap:tool:meshrix.workspace.file.read:execute": "read_only",
  "cap:tool:meshrix.workspace.file.write:execute": "safe_write",
  "cap:tool:meshrix.workspace.file.patch:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.submit:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.list:execute": "read_only",
  "cap:tool:meshrix.workspace.contribution.leaderboard:execute": "read_only",
  "cap:tool:meshrix.workspace.contribution.stats:execute": "read_only",
  "cap:tool:meshrix.workspace.contribution.report:execute": "read_only",
  "cap:tool:meshrix.workspace.contribution.assets.list:execute": "read_only",
  "cap:tool:meshrix.workspace.contribution.permission.request:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.permission.grant:execute": "repair_write",
  "cap:tool:meshrix.workspace.contribution.scan:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.review:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.preview:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.publish:execute": "repair_write",
  "cap:tool:meshrix.workspace.contribution.adopt:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.reject:execute": "repair_write",
  "cap:tool:meshrix.workspace.contribution.requestChanges:execute": "safe_write",
  "cap:tool:meshrix.workspace.contribution.revoke:execute": "repair_write",
  "cap:tool:meshrix.workspace.proposal.create:execute": "safe_write",
  "cap:tool:meshrix.workspace.proposal.apply:execute": "repair_write",
  "cap:tool:meshrix.workspace.asset.policy.set:execute": "repair_write",
  "cap:tool:meshrix.workspace.asset.permission.check:execute": "read_only",
  "cap:tool:meshrix.workspace.asset.target.connect:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.list:execute": "read_only",
  "cap:tool:meshrix.workspace.asset.read:execute": "read_only",
  "cap:tool:meshrix.workspace.asset.submit:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.mutate:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.sync.plan:execute": "read_only",
  "cap:tool:meshrix.workspace.asset.sync.apply:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.import:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.export:execute": "repair_write",
  "cap:tool:meshrix.workspace.asset.review.comment:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.review.requestChanges:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.review.approve:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.checkpoint:execute": "safe_write",
  "cap:tool:meshrix.workspace.asset.lineage:execute": "read_only",
  "cap:tool:meshrix.workspace.asset.receipt.get:execute": "read_only",
  "cap:tool:meshrix.workspace.asset.backfill:execute": "repair_write",
  "cap:tool:meshrix.workspace.audit.query:execute": "read_only",
  "cap:tool:meshrix.workspace.operation.history:execute": "read_only",
  "cap:tool:meshrix.workspace.checkpoint.tree.list:execute": "read_only",
  "cap:tool:meshrix.workspace.checkpoint.node.get:execute": "read_only",
  "cap:tool:meshrix.workspace.checkpoint.diff:execute": "read_only",
  "cap:tool:meshrix.workspace.checkpoint.restore.preview:execute": "repair_write",
  "cap:tool:meshrix.workspace.checkpoint.restore:execute": "repair_write",
  "cap:tool:meshrix.workspace.checkpoint.scope.query:execute": "read_only",
  "cap:tool:meshrix.workspace.operation.revert.scope:execute": "repair_write",
  "cap:tool:meshrix.workspace.operation.revert.apply:execute": "repair_write",
  "cap:tool:meshrix.gateway.externalServices.publications.list:execute": "read_only",
  "cap:tool:meshrix.gateway.externalServices.publications.get:execute": "read_only",
  "cap:tool:meshrix.gateway.externalServices.create:execute": "safe_write",
  "cap:tool:meshrix.gateway.externalServices.replace:execute": "safe_write",
  "cap:tool:meshrix.gateway.externalServices.disable:execute": "safe_write",
  "cap:tool:meshrix.gateway.externalServices.remove:execute": "repair_write",
  "cap:tool:meshrix.gateway.externalServices.republish:execute": "safe_write",
  "cap:tool:meshrix.gateway.externalServices.list:execute": "read_only",
  "cap:tool:meshrix.gateway.externalServices.get:execute": "read_only",
  "cap:tool:meshrix.gateway.externalServices.health:execute": "read_only",
  "cap:tool:meshrix.gateway.policyPreview:execute": "read_only",
  "cap:tool:meshrix.gateway.forward:execute": "safe_write",
  "cap:tool:meshrix.gateway.payloadTransit:execute": "safe_write",
  "cap:tool:meshrix.gateway.artifacts.get:execute": "read_only",
  "cap:tool:meshrix.gateway.audit:execute": "read_only",
  "cap:tool:meshrix.gateway.metrics:execute": "read_only",
  "cap:tool:meshrix.securityAlerts.list:execute": "read_only",
  "cap:tool:meshrix.securityAlerts.ack:execute": "safe_write",
  "cap:tool:meshrix.securityAlerts.export:execute": "read_only",
  "cap:tool:meshrix.securityAlerts.prune:execute": "repair_write",
  "cap:tool:system.health:execute": "read_only",
  "cap:tool:meshrix.architecture.liveMap:execute": "read_only",
  "cap:tool:meshrix.sampleCapabilityPack.list:execute": "read_only",
  "cap:tool:meshrix.sampleCapabilityPack.get:execute": "read_only",
  "cap:tool:meshrix.sampleCapabilityPack.materialize:execute": "safe_write",
  "cap:tool:meshrix.executiveReport.list:execute": "read_only",
  "cap:tool:meshrix.executiveReport.preview:execute": "read_only",
  "cap:tool:meshrix.executiveReport.generate:execute": "safe_write",
  "cap:tool:meshrix.workspaceGovernance.describe:execute": "read_only",
  "cap:tool:meshrix.workspaceGovernance.policy.set:execute": "repair_write",
  "cap:tool:meshrix.workspaceGovernance.evaluate:execute": "safe_write",
  "cap:tool:meshrix.workspaceGovernance.shareGrant:execute": "safe_write",
  "cap:tool:meshrix.agentSync.config.get:execute": "read_only",
  "cap:tool:meshrix.agentSync.config.set:execute": "repair_write",
  "cap:tool:meshrix.agentSync.publish:execute": "safe_write",
  "cap:tool:meshrix.agentSync.subscribe:execute": "read_only",
  "cap:tool:meshrix.runtime.info:execute": "read_only",
  "cap:tool:meshrix.runtime.mounts:execute": "read_only",
  "cap:tool:meshrix.runtime.mounts.set:execute": "repair_write",
  "cap:tool:meshrix.runtime.mounts.reload:execute": "repair_write",
  "cap:tool:meshrix.strategy.describe:execute": "read_only",
  "cap:tool:meshrix.strategy.workflowPolicy.evaluate:execute": "read_only",
  "cap:tool:meshrix.strategy.agentPolicy.evaluate:execute": "read_only",
  "cap:tool:meshrix.strategy.routePolicy.evaluate:execute": "read_only",
  "cap:tool:meshrix.strategy.queuePolicy.evaluate:execute": "read_only",
  "cap:tool:meshrix.strategy.toolPolicy.preview:execute": "read_only",
  "cap:tool:meshrix.operationPermission.apiKeys.issuerScopes:execute": "read_only",
  "cap:tool:meshrix.operationPermission.apiKeys.list:execute": "read_only",
  "cap:tool:meshrix.operationPermission.apiKeys.create:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.apiKeys.rotate:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.apiKeys.revoke:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.catalog:execute": "read_only",
  "cap:tool:meshrix.operationPermission.catalogItem:execute": "read_only",
  "cap:tool:meshrix.operationPermission.toolsets:execute": "read_only",
  "cap:tool:meshrix.operationPermission.toolsetsResolve:execute": "read_only",
  "cap:tool:meshrix.operationPermission.profiles:execute": "read_only",
  "cap:tool:meshrix.operationPermission.policyEvaluate:execute": "read_only",
  "cap:tool:meshrix.operationPermission.policyPreview:execute": "read_only",
  "cap:tool:meshrix.operationPermission.grants:execute": "read_only",
  "cap:tool:meshrix.operationPermission.createGrant:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.updateGrant:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.rotateGrant:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.revokeGrant:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.audit:execute": "read_only",
  "cap:tool:meshrix.operationPermission.auditItem:execute": "read_only",
  "cap:tool:meshrix.operationPermission.metricsSummary:execute": "read_only",
  "cap:tool:meshrix.operationPermission.metricsExport:execute": "read_only",
  "cap:tool:meshrix.operationPermission.metricsHealth:execute": "read_only",
  "cap:tool:meshrix.operationPermission.metricsPrometheus:execute": "read_only",
  "cap:tool:meshrix.operationPermission.metricsStorage:execute": "read_only",
  "cap:tool:meshrix.operationPermission.metricsPrune:execute": "repair_write",
  "cap:tool:meshrix.operationPermission.events:execute": "read_only",
  "cap:tool:meshrix.operationPermission.pendingOperations.list:execute": "read_only",
  "cap:tool:meshrix.operationPermission.pendingOperations.resolve:execute": "repair_write",
  "cap:tool:meshrix.storageSummary:execute": "read_only",
  "cap:tool:meshrix.storageBackups.list:execute": "read_only",
  "cap:tool:meshrix.storageBackups.create:execute": "safe_write",
  "cap:tool:meshrix.storageBackups.restorePreview:execute": "read_only",
  "cap:tool:meshrix.storageBackups.restore:execute": "repair_write",
  "cap:tool:meshrix.agentWorkspace.create:execute": "safe_write",
  "cap:tool:meshrix.workspace.create:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.list:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.get:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.delete:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.folder.create:execute": "safe_write",
  "cap:tool:meshrix.workspace.folder.create:execute": "safe_write",
  "cap:tool:meshrix.agentSession.list:execute": "read_only",
  "cap:tool:meshrix.agentSession.get:execute": "read_only",
  "cap:tool:meshrix.agentSession.context:execute": "read_only",
  "cap:tool:meshrix.agentSession.events.append:execute": "safe_write",
  "cap:tool:meshrix.agentSession.fork:execute": "safe_write",
  "cap:tool:meshrix.agentSession.compare:execute": "read_only",
  "cap:tool:meshrix.agentSession.mergeProposal:execute": "safe_write",
  "cap:tool:meshrix.agentSession.archive:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.submissionResolve:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.issueResolve:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.locks:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.lock:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.files.list:execute": "read_only",
  "cap:tool:meshrix.workspace.files.list:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.file.upload:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.file.stat:execute": "read_only",
  "cap:tool:meshrix.workspace.file.stat:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.file.download:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.file.write:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.file.delete:execute": "safe_write",
  "cap:tool:meshrix.workspace.file.delete:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.file.move:execute": "safe_write",
  "cap:tool:meshrix.workspace.file.move:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.context:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.contextBundle.export:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.contextBundle.restore:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.chain:execute": "read_only",
  "cap:tool:meshrix.agentWorkspace.parent.set:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.profile.hotswap:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.sources.set:execute": "safe_write",
  "cap:tool:meshrix.agentWorkspace.share:execute": "repair_write",
  "cap:tool:meshrix.agentWorkspace.unshare:execute": "safe_write",
  "cap:tool:meshrix.context.profiles:execute": "read_only",
  "cap:tool:meshrix.context.profiles.set:execute": "safe_write",
  "cap:tool:meshrix.agentMemory.sessionMemory.get:execute": "read_only",
  "cap:tool:meshrix.agentMemory.sessionMemory.clear:execute": "repair_write",
  "cap:tool:uploads.create_session:execute": "safe_write",
  "cap:tool:uploads.get_session:execute": "read_only",
  "cap:tool:uploads.upload_chunk:execute": "safe_write",
  "cap:tool:meshrix.jobs.uploadWorkspaceMaterialize:execute": "repair_write",
  "cap:tool:meshrix.jobs.list:execute": "read_only",
  "cap:tool:meshrix.jobs.workQueue.inspect:execute": "read_only",
  "cap:tool:meshrix.jobs.workQueue.pause:execute": "safe_write",
  "cap:tool:meshrix.jobs.workQueue.resume:execute": "safe_write",
  "cap:tool:meshrix.jobs.workQueue.drain:execute": "safe_write",
  "cap:tool:meshrix.jobs.workQueue.recoverFailed:execute": "safe_write",
  "cap:tool:meshrix.jobs.workQueue.rebuild:execute": "repair_write",
  "cap:tool:meshrix.jobs.get:execute": "read_only"
});
